module.exports = {
  ROLES: { ADMIN: 'admin', USER: 'user' },
  ORDER_TYPES: { BUY: 'BUY', SELL: 'SELL' },
  ORDER_STATUS: { PENDING: 'PENDING', EXECUTED: 'EXECUTED', CANCELLED: 'CANCELLED', FAILED: 'FAILED' },
  POSITION_STATUS: { OPEN: 'OPEN', CLOSED: 'CLOSED' },
  PAYMENT_STATUS: { PENDING: 'PENDING', SUCCESS: 'SUCCESS', FAILED: 'FAILED' },
  EXCHANGE_TYPES: { NSE: 'NSE', BSE: 'BSE', NFO: 'NFO', MCX: 'MCX' },
  WS_EXCHANGE_TYPE: { NSE_CM: 1, NSE_FO: 2, BSE_CM: 3, BSE_FO: 4, MCX_FO: 5 },
  WS_SUBSCRIPTION_MODE: { LTP: 1, QUOTE: 2, SNAP_QUOTE: 3 },
  WS_ACTION: { SUBSCRIBE: 1, UNSUBSCRIBE: 0 },
  INITIAL_BALANCE: 10000000,   // 1 crore — given on registration (trial)
  DUMMY_BALANCE: 50000000,    // 5 crore — given after ₹500 payment & reset daily
  PAYMENT_AMOUNT: 500,
  PLATFORM_FEE: 99,
  CREDIT_AMOUNT: 401,
  TRADE_FEE: 2,
  TRIAL_HOURS: 48,
};
