export const designTokens = {
  colors: {
    brand: "#E11D2E",
    ink: "#182338",
    muted: "#738096",
    background: "#F5F7FB",
    surface: "#FFFFFF",
    border: "#E5EAF2",
    sidebar: "#101827",
    sidebarMuted: "#96A2B8",
    blue: "#4263EB",
    green: "#16835D",
    red: "#D53445",
  },
  radius: { card: 12, control: 8 },
  spacing: [4, 8, 12, 16, 20, 24, 32],
  shadow: "0 2px 8px rgba(24, 35, 56, 0.04)",
  font: '"Inter", "Segoe UI", sans-serif',
};
export const cssVariables = {
  "--bg": designTokens.colors.background,
  "--surface": designTokens.colors.surface,
  "--border": designTokens.colors.border,
  "--muted": designTokens.colors.muted,
  "--ink": designTokens.colors.ink,
  "--red": designTokens.colors.red,
  "--brand": designTokens.colors.brand,
  "--green": designTokens.colors.green,
  "--blue": designTokens.colors.blue,
  "--sidebar": designTokens.colors.sidebar,
  "--sidebar-muted": designTokens.colors.sidebarMuted,
  "--card-radius": `${designTokens.radius.card}px`,
  "--control-radius": `${designTokens.radius.control}px`,
  "--card-shadow": designTokens.shadow,
  "--font": designTokens.font,
};
